db:
  file: "db/db.sqlite3"
wav:
  folder: "wav/"
template:
  # "folder" cannot be used yet, see comment in SointuService
  folder: "templates/"
  instrument: "./instrument.yml"
  sequence: "./sequence.yml"
  asm: "./wav.asm"