db:
  file: "db/db.sqlite3"
wav:
  folder: "wav/"
template:
  folder: "templates/"
  test_instrument: "./test_instrument.yml"  # only for testing / debug stuff
  sequence: "./sequence.yml"  # doesn't change for now
  asm: "./wav.asm"  # doesn't change for now
instruments:
  folder: "instruments/"
