db:
  file: "db/db.sqlite3"
wav:
  folder: "wav/"
template:
  folder: "templates/"
  instrument: "./instrument.yml"  # this file will be written by the instruments service
  sequence: "./sequence.yml"  # doesn't change for now
  asm: "./wav.asm"  # doesn't change for now
instruments:
  folder: "instruments/"
